site_name: Hacking Mabu 2
site_url: https://electronick-co.github.io/hacking_mabu2/
theme:
  name: material

  features:
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow    
  
  plugins:
  - search
  - blog

# Page tree
nav:
  - Home: 
    - index.md
    - about.md
  - Quick start guide: 
    - quickstart_guide.md
  - Hacking process:
    - subsystems/animatronics.md
    - subsystems/tablet.md
  - Blog: 
    - blog/index.md